# Generated by Django 3.2.2 on 2021-05-11 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
