# Generated by Django 3.2.2 on 2021-05-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
